import {
  QR_STATUS_BODY_SCHEMA,
  apiEnvelopeSchema,
  authCsrfResponseEnvelopeSchema,
  authLoginResponseEnvelopeSchema,
  authRefreshResponseEnvelopeSchema,
  authRegisterResponseEnvelopeSchema,
  confirmPasswordBodySchema,
  frontendTextEnvelopeSchema,
  frontendUnknownEnvelopeSchema,
  genericSuccessEnvelopeSchema,
  loginBodySchema,
  mfaDisableBodySchema,
  mfaEnableBodySchema,
  mfaQrApproveBodySchema,
  mfaQrPollResponseEnvelopeSchema,
  mfaQrSessionCreateBodySchema,
  mfaQrSessionIdBodySchema,
  mfaQrSessionResponseEnvelopeSchema,
  mfaResetLinkBodySchema,
  mfaSetupBodySchema,
  mfaSetupResponseEnvelopeSchema,
  mfaVerifyBodySchema,
  passwordResetBodySchema,
  registerBodySchema,
  sensitiveConfirmResponseEnvelopeSchema,
  tokenImportProxyBodySchema,
  tokenImportProxyRawResponseSchema,
  wechatHortorLoginBodySchema,
  wechatHortorLoginHeaderSchema,
  wechatHortorLoginRequestSchema,
  wechatProxyRawTextResponseSchema,
  wechatQrConnectRequestSchema,
  mfaEnableResponseEnvelopeSchema,
} from "./hardeningSchemas.js";

const makeContract = ({
  operationId,
  method,
  path,
  tag,
  summary,
  requestBody = null,
  requestHeaders = null,
  openapiSuccessSchema,
  openapiSuccessContentTypes = ["application/json"],
  frontendRequestSchema = requestBody,
  frontendResponseSchema = null,
  runtimeAccessor,
}) => ({
  operationId,
  method,
  path,
  tag,
  summary,
  requestBody,
  requestHeaders,
  openapiSuccessSchema,
  openapiSuccessContentTypes,
  frontendRequestSchema,
  frontendResponseSchema,
  runtimeAccessor,
});

export const hardeningContracts = [
  makeContract({
    operationId: "login",
    method: "post",
    path: "/api/v1/auth/login",
    tag: "Auth",
    summary: "用户名密码登录",
    requestBody: loginBodySchema,
    openapiSuccessSchema: authLoginResponseEnvelopeSchema,
    frontendResponseSchema: authLoginResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.login",
  }),
  makeContract({
    operationId: "register",
    method: "post",
    path: "/api/v1/auth/register",
    tag: "Auth",
    summary: "注册账号",
    requestBody: registerBodySchema,
    openapiSuccessSchema: authRegisterResponseEnvelopeSchema,
    frontendResponseSchema: authRegisterResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.register",
  }),
  makeContract({
    operationId: "resetPassword",
    method: "post",
    path: "/api/v1/auth/password-reset",
    tag: "Auth",
    summary: "重置密码",
    requestBody: passwordResetBodySchema,
    openapiSuccessSchema: genericSuccessEnvelopeSchema,
    frontendResponseSchema: genericSuccessEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.resetPassword",
  }),
  makeContract({
    operationId: "refreshToken",
    method: "post",
    path: "/api/v1/auth/refresh",
    tag: "Auth",
    summary: "刷新访问令牌",
    openapiSuccessSchema: authRefreshResponseEnvelopeSchema,
    frontendResponseSchema: authRefreshResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.refreshToken",
  }),
  makeContract({
    operationId: "logout",
    method: "post",
    path: "/api/v1/auth/logout",
    tag: "Auth",
    summary: "退出登录",
    openapiSuccessSchema: genericSuccessEnvelopeSchema,
    frontendResponseSchema: genericSuccessEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.logout",
  }),
  makeContract({
    operationId: "getMe",
    method: "get",
    path: "/api/v1/auth/me",
    tag: "Auth",
    summary: "获取当前用户信息",
    openapiSuccessSchema: authLoginResponseEnvelopeSchema,
    frontendResponseSchema: authLoginResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.getMe",
  }),
  makeContract({
    operationId: "ensureCsrf",
    method: "get",
    path: "/api/v1/auth/csrf",
    tag: "Auth",
    summary: "获取 CSRF 令牌",
    openapiSuccessSchema: authCsrfResponseEnvelopeSchema,
    frontendResponseSchema: authCsrfResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.ensureCsrf",
  }),
  makeContract({
    operationId: "verifyMfa",
    method: "post",
    path: "/api/v1/auth/mfa/verify",
    tag: "MFA",
    summary: "提交 MFA 验证码",
    requestBody: mfaVerifyBodySchema,
    openapiSuccessSchema: authLoginResponseEnvelopeSchema,
    frontendResponseSchema: authLoginResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.verifyMfa",
  }),
  makeContract({
    operationId: "createMfaQrSession",
    method: "post",
    path: "/api/v1/auth/mfa/qr/session",
    tag: "MFA",
    summary: "创建 MFA 二维码会话",
    requestBody: mfaQrSessionCreateBodySchema,
    openapiSuccessSchema: mfaQrSessionResponseEnvelopeSchema,
    frontendResponseSchema: mfaQrSessionResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.createMfaQrSession",
  }),
  makeContract({
    operationId: "approveMfaQr",
    method: "post",
    path: "/api/v1/auth/mfa/qr/approve",
    tag: "MFA",
    summary: "确认 MFA 二维码会话",
    requestBody: mfaQrApproveBodySchema,
    openapiSuccessSchema: genericSuccessEnvelopeSchema,
    frontendResponseSchema: genericSuccessEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.approveMfaQr",
  }),
  makeContract({
    operationId: "pollMfaQr",
    method: "post",
    path: "/api/v1/auth/mfa/qr/poll",
    tag: "MFA",
    summary: "轮询 MFA 二维码会话状态",
    requestBody: mfaQrSessionIdBodySchema,
    openapiSuccessSchema: mfaQrPollResponseEnvelopeSchema,
    frontendResponseSchema: mfaQrPollResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.pollMfaQr",
  }),
  makeContract({
    operationId: "setupMfa",
    method: "post",
    path: "/api/v1/auth/mfa/setup",
    tag: "MFA",
    summary: "初始化 MFA",
    requestBody: mfaSetupBodySchema,
    openapiSuccessSchema: mfaSetupResponseEnvelopeSchema,
    frontendResponseSchema: mfaSetupResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.setupMfa",
  }),
  makeContract({
    operationId: "enableMfa",
    method: "post",
    path: "/api/v1/auth/mfa/enable",
    tag: "MFA",
    summary: "启用 MFA",
    requestBody: mfaEnableBodySchema,
    openapiSuccessSchema: mfaEnableResponseEnvelopeSchema,
    frontendResponseSchema: mfaEnableResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.enableMfa",
  }),
  makeContract({
    operationId: "disableMfa",
    method: "post",
    path: "/api/v1/auth/mfa/disable",
    tag: "MFA",
    summary: "关闭 MFA",
    requestBody: mfaDisableBodySchema,
    openapiSuccessSchema: genericSuccessEnvelopeSchema,
    frontendResponseSchema: genericSuccessEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.disableMfa",
  }),
  makeContract({
    operationId: "resetMfaByLink",
    method: "post",
    path: "/api/v1/auth/mfa/reset-by-link",
    tag: "MFA",
    summary: "使用重置链接关闭 MFA",
    requestBody: mfaResetLinkBodySchema,
    openapiSuccessSchema: genericSuccessEnvelopeSchema,
    frontendResponseSchema: genericSuccessEnvelopeSchema,
    runtimeAccessor: "runtimeApi.auth.resetMfaByLink",
  }),
  makeContract({
    operationId: "confirmUserSensitiveAction",
    method: "post",
    path: "/api/v1/user/confirm-password",
    tag: "SensitiveAction",
    summary: "用户敏感操作二次确认",
    requestBody: confirmPasswordBodySchema,
    openapiSuccessSchema: sensitiveConfirmResponseEnvelopeSchema,
    frontendResponseSchema: sensitiveConfirmResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.user.confirmSensitiveAction",
  }),
  makeContract({
    operationId: "confirmAdminSensitiveAction",
    method: "post",
    path: "/api/v1/admin/confirm-password",
    tag: "SensitiveAction",
    summary: "管理员敏感操作二次确认",
    requestBody: confirmPasswordBodySchema,
    openapiSuccessSchema: sensitiveConfirmResponseEnvelopeSchema,
    frontendResponseSchema: sensitiveConfirmResponseEnvelopeSchema,
    runtimeAccessor: "runtimeApi.admin.confirmSensitiveAction",
  }),
  makeContract({
    operationId: "tokenImportProxyFetch",
    method: "post",
    path: "/api/v1/token-import/proxy",
    tag: "Proxy",
    summary: "代理获取导入 JSON",
    requestBody: tokenImportProxyBodySchema,
    openapiSuccessSchema: tokenImportProxyRawResponseSchema,
    frontendResponseSchema: frontendUnknownEnvelopeSchema,
    runtimeAccessor: "runtimeApi.tokenImport.proxyFetch",
  }),
  makeContract({
    operationId: "wechatQrConnect",
    method: "get",
    path: "/api/v1/wechat-proxy/qrconnect",
    tag: "Proxy",
    summary: "获取微信二维码 HTML",
    openapiSuccessSchema: wechatProxyRawTextResponseSchema,
    openapiSuccessContentTypes: ["text/html", "application/xhtml+xml"],
    frontendRequestSchema: wechatQrConnectRequestSchema,
    frontendResponseSchema: frontendTextEnvelopeSchema,
    runtimeAccessor: "runtimeApi.wechatProxy.qrConnect",
  }),
  makeContract({
    operationId: "wechatQrStatus",
    method: "post",
    path: "/api/v1/wechat-proxy/qrstatus",
    tag: "Proxy",
    summary: "轮询微信二维码状态",
    requestBody: QR_STATUS_BODY_SCHEMA,
    openapiSuccessSchema: wechatProxyRawTextResponseSchema,
    openapiSuccessContentTypes: ["text/plain", "text/html"],
    frontendResponseSchema: frontendTextEnvelopeSchema,
    runtimeAccessor: "runtimeApi.wechatProxy.qrStatus",
  }),
  makeContract({
    operationId: "wechatHortorLogin",
    method: "post",
    path: "/api/v1/wechat-proxy/hortor-login",
    tag: "Proxy",
    summary: "代理转发 Hortor 登录请求",
    requestBody: wechatHortorLoginBodySchema,
    requestHeaders: wechatHortorLoginHeaderSchema,
    openapiSuccessSchema: wechatProxyRawTextResponseSchema,
    openapiSuccessContentTypes: ["application/json", "application/*+json", "text/plain"],
    frontendRequestSchema: wechatHortorLoginRequestSchema,
    frontendResponseSchema: frontendTextEnvelopeSchema,
    runtimeAccessor: "runtimeApi.wechatProxy.hortorLogin",
  }),
];
