import {
  createCombatBatchTaskDeps,
  createDailyBatchTaskDeps,
  createResourceBatchTaskDeps,
  createSharedBatchTaskDeps,
} from "./batchTaskDepBuilders.js";

export function createBatchTaskDeps({
  addLog,
  autoScrollLog,
  batchSettings,
  calculateMonthProgress,
  canClaim,
  connectionQueue,
  currentRunningTokenId,
  currentSettings,
  ensureConnection,
  getTodayStartSec,
  giftQuantity,
  gradeLabel,
  helperSettings,
  isRunning,
  isTodayAvailable,
  loadSettings,
  logContainer,
  logs,
  message,
  nextTick,
  normalizeCars,
  pickArenaTargetId,
  recipientIdInput,
  recipientInfo,
  releaseConnectionSlot,
  securityPassword,
  selectedTokens,
  shouldSendCar,
  shouldStop,
  tokenStatus,
  tokenStore,
  tokens,
}) {
  const params = {
    addLog,
    autoScrollLog,
    batchSettings,
    calculateMonthProgress,
    canClaim,
    connectionQueue,
    currentRunningTokenId,
    currentSettings,
    ensureConnection,
    getTodayStartSec,
    giftQuantity,
    gradeLabel,
    helperSettings,
    isRunning,
    isTodayAvailable,
    loadSettings,
    logContainer,
    logs,
    message,
    nextTick,
    normalizeCars,
    pickArenaTargetId,
    recipientIdInput,
    recipientInfo,
    releaseConnectionSlot,
    securityPassword,
    selectedTokens,
    shouldSendCar,
    shouldStop,
    tokenStatus,
    tokenStore,
    tokens,
  };

  const sharedDeps = createSharedBatchTaskDeps(params);
  const dailyDeps = createDailyBatchTaskDeps(sharedDeps, params);
  const combatDeps = createCombatBatchTaskDeps(sharedDeps, params);
  const resourceDeps = createResourceBatchTaskDeps(sharedDeps, params);

  return {
    ...sharedDeps,
    ...dailyDeps,
    ...combatDeps,
    ...resourceDeps,
    daily: dailyDeps,
    combat: combatDeps,
    resource: resourceDeps,
  };
}
